// Generated by Gemini 3 Pro with /src/sunflower/adapter/buildin/gemini.ts and /src/renderer/packages/web-search/bing.ts (from http://github.com/chatboxai/chatbox.git) as references
// Haven't tried whether this is usable yet
import Adapter from "..";
import type AdapterConfig from "../config";
import {
  type Message,
  type GenerateOptions,
  type MessagePartUnion,
} from "../message";
import type Tools from "@/sunflower/tools";

// 引入 OpenAI 官方 SDK
import OpenAIClient from "openai";
import type {
  ChatCompletionMessageParam,
  ChatCompletionTool,
  ChatCompletionContentPart,
  ChatCompletionChunk,
  ChatCompletionMessageToolCall,
} from "openai/resources/chat/completions";

// 引入 JSDOM 用于解析 Bing 搜索结果的 HTML
import { JSDOM } from "jsdom";

/**
 * 扩展 GenerateOptions 以支持 OpenAI 特有参数
 */
interface OpenAIGenerateOptions extends GenerateOptions {
  temperature?: number;
  max_tokens?: number;
}

/**
 * ============================================================
 * 工具类：BingSearch
 * ============================================================
 */
interface SearchResultItem {
  title: string;
  link: string;
  snippet: string;
}

class BingSearch {
  async search(query: string, signal?: AbortSignal): Promise<string> {
    const html = await this.fetchSerp(query, signal);
    const items = this.extractItems(html);
    return JSON.stringify(items.slice(0, 16));
  }

  private async fetchSerp(query: string, signal?: AbortSignal): Promise<string> {
    const url = new URL("https://www.bing.com/search");
    url.searchParams.append("q", query);

    const headers = {
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept-Language": "en-US,en;q=0.9",
    };

    const res = await fetch(url.toString(), {
      method: "GET",
      headers,
      signal,
    });

    if (!res.ok) {
      throw new Error(
        `Bing search failed with status: ${res.status} ${res.statusText}`
      );
    }

    return await res.text();
  }

  private extractItems(html: string): SearchResultItem[] {
    const dom = new JSDOM(html);
    const doc = dom.window.document;
    const nodes = doc.querySelectorAll("#b_results > li.b_algo");

    return Array.from(nodes).map((node: any) => {
      const titleNode = node.querySelector("h2 > a");
      const title = titleNode?.textContent || "No Title";
      const link = titleNode?.getAttribute("href") || "";
      const snippetNode = node.querySelector("p[class^='b_lineclamp']");
      const snippet = snippetNode?.textContent || "";
      return { title, link, snippet };
    });
  }
}

/**
 * ============================================================
 * 辅助函数：图片转 Base64
 * ============================================================
 */
async function urlToBase64(url: string): Promise<string> {
  if (url.startsWith("data:")) return url;

  try {
    const response = await fetch(url);
    if (!response.ok) {
      console.warn(`[OpenAI Adapter] Failed to fetch image: ${url}`);
      return url;
    }

    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const contentType = response.headers.get("content-type") || "image/jpeg";

    return `data:${contentType};base64,${buffer.toString("base64")}`;
  } catch (error) {
    console.error(`[OpenAI Adapter] Error converting image to base64:`, error);
    return url;
  }
}

const BING_TOOL_DEFINITION: ChatCompletionTool = {
  type: "function",
  function: {
    name: "bing_search",
    description:
      "Search the internet using Bing to get up-to-date information, news, or website content.",
    parameters: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "The search keywords.",
        },
      },
      required: ["query"],
    },
  },
};

/**
 * ============================================================
 * OpenAI Adapter 主类
 * ============================================================
 */
export default class OpenAI extends Adapter {
  id: string = "openai";
  config: AdapterConfig;

  private _tools: Tools[] = [];
  private _openai_tools_definitions: ChatCompletionTool[] = [];
  private client: OpenAIClient;

  get tools(): Tools[] {
    return this._tools;
  }

  set tools(tools: Tools[]) {
    this._tools = tools;
    this._updateToolDefinitions();
  }

  constructor(config: AdapterConfig, tools: Tools[] = []) {
    super();
    this.config = config;

    this.client = new OpenAIClient({
      apiKey: config.api_key,
      baseURL: config.base_url,
      dangerouslyAllowBrowser: true,
    });

    this.tools = tools;
  }

  private _updateToolDefinitions() {
    const userTools = this._tools.map((tool): ChatCompletionTool => ({
      type: "function",
      function: {
        name: tool.name,
        description: tool.description,
        parameters: {
          type: "object",
          properties: tool.parameters,
          required: tool.required,
        },
      },
    }));
    this._openai_tools_definitions = [...userTools, BING_TOOL_DEFINITION];
  }

  private async messagesToOpenAI(
    messages: Message[]
  ): Promise<ChatCompletionMessageParam[]> {
    const result: ChatCompletionMessageParam[] = [];

    for (const msg of messages) {
      if (msg.role === "system") {
        const content = msg.parts?.[0]?.content;
        if (typeof content === "string") {
          result.push({ role: "system", content });
        }
        continue;
      }

      const role = msg.role === "assistant" ? "assistant" : "user";
      const contentParts: ChatCompletionContentPart[] = [];

      for (const part of msg.parts) {
        if (part.type === "text") {
          contentParts.push({ type: "text", text: part.content });
        } else if (part.type === "image") {
          const base64Url = await urlToBase64(part.content.url);
          contentParts.push({
            type: "image_url",
            image_url: {
              url: base64Url,
              detail: "auto",
            },
          });
        }
      }

      if (contentParts.length > 0) {
        if (role === "assistant") {
          result.push({
            role: "assistant",
            content: contentParts as any, // 强制转换以兼容 mixed content
          });
        } else {
          result.push({
            role: "user",
            content: contentParts,
          });
        }
      }
    }
    return result;
  }

  async generate(
    message: Message[],
    options?: GenerateOptions
  ): Promise<Message> {
    const currentMessages = await this.messagesToOpenAI(message);
    const opts = options as OpenAIGenerateOptions;

    // 递归函数
    const processGeneration = async (
      messages: ChatCompletionMessageParam[]
    ): Promise<Message> => {
      const response = await this.client.chat.completions.create({
        model: opts?.model ?? this.config.model,
        messages: messages,
        tools:
          this._openai_tools_definitions.length > 0
            ? this._openai_tools_definitions
            : undefined,
        tool_choice: "auto",
        temperature: opts?.temperature,
        max_tokens: opts?.max_tokens,
      });

      const choice = response.choices[0];
      if (!choice) throw new Error("No response from OpenAI");

      const responseMsg = choice.message;

      const finalRes: Message = {
        role: "assistant",
        parts: [],
      };

      if (responseMsg.content) {
        finalRes.parts.push({ type: "text", content: responseMsg.content });
      }

      if (responseMsg.tool_calls && responseMsg.tool_calls.length > 0) {
        messages.push(responseMsg);

        for (const toolCall of responseMsg.tool_calls) {
          // --- 修复点开始 ---
          // 必须先判断 type 是否为 'function'，才能安全访问 .function 属性
          if (toolCall.type !== "function") {
            continue; 
          }
          
          const fnName = toolCall.function.name;
          const fnArgsStr = toolCall.function.arguments;
          // --- 修复点结束 ---

          let toolResultStr = "";

          try {
            const fnArgs = JSON.parse(fnArgsStr);
            if (fnName === "bing_search") {
              const bing = new BingSearch();
              toolResultStr = await bing.search(fnArgs.query);
            } else {
              const tool = this.tools.find((t) => t.name === fnName);
              if (tool) {
                toolResultStr = await tool.call(fnArgs);
              } else {
                toolResultStr = JSON.stringify({
                  error: `Tool ${fnName} not found.`,
                });
              }
            }
          } catch (e: any) {
            toolResultStr = JSON.stringify({
              error: e.message || "Unknown error in tool execution",
            });
          }

          // 将结果作为 Tool Message 添加
          messages.push({
            role: "tool",
            tool_call_id: toolCall.id,
            content: toolResultStr,
          });

          // 记录在本次返回的 parts 中 (可选，用于前端展示工具使用情况)
          finalRes.parts.push({
            type: "text",
            content: `\n[Tool Used: ${fnName}]\n`,
          } as any);
        }

        // 递归：将工具结果发回给 LLM
        const nextResponse = await processGeneration(messages);
        finalRes.parts.push(...nextResponse.parts);
      }

      return finalRes;
    };

    return processGeneration(currentMessages);
  }

  async *generate_stream(
    message: Message[],
    options?: GenerateOptions
  ): AsyncGenerator<MessagePartUnion> {
    const currentMessages = await this.messagesToOpenAI(message);
    const opts = options as OpenAIGenerateOptions;

    const streamGenerator = async function* (
      client: OpenAIClient,
      messages: ChatCompletionMessageParam[],
      adapter: OpenAI
    ): AsyncGenerator<MessagePartUnion> {
      const stream = await client.chat.completions.create({
        model: opts?.model ?? adapter.config.model,
        messages: messages,
        tools:
          adapter._openai_tools_definitions.length > 0
            ? adapter._openai_tools_definitions
            : undefined,
        stream: true,
      });

      // 暂存流式返回的工具调用片段
      let toolCallsBuffer: Record<
        number,
        // 这里使用 DeepPartial 或者手动构造结构，
        // 实际上我们只需要收集 id, function.name, function.arguments
        {
           index: number;
           id?: string;
           type?: string;
           function: { name: string; arguments: string };
        }
      > = {};

      for await (const chunk of stream) {
        const delta = chunk.choices[0]?.delta;
        if (!delta) continue;

        if (delta.content) {
          yield { type: "text", content: delta.content };
        }

        if (delta.tool_calls) {
          for (const tc of delta.tool_calls) {
            const index = tc.index;
            if (!toolCallsBuffer[index]) {
              toolCallsBuffer[index] = {
                index,
                id: tc.id,
                type: tc.type,
                function: { name: "", arguments: "" },
              };
            }

            if (tc.function?.name) {
              toolCallsBuffer[index].function.name += tc.function.name;
            }
            if (tc.function?.arguments) {
              toolCallsBuffer[index].function.arguments += tc.function.arguments;
            }
            // type 和 id 通常只出现在第一个 chunk
            if (tc.type) toolCallsBuffer[index].type = tc.type;
            if (tc.id) toolCallsBuffer[index].id = tc.id;
          }
        }
      }

      const toolCalls = Object.values(toolCallsBuffer);

      if (toolCalls.length > 0) {
        // 构造完整的 Assistant Message
        const assistantMsg: ChatCompletionMessageParam = {
          role: "assistant",
          content: null,
          tool_calls: toolCalls.map((tc) => ({
            id: tc.id!,
            type: "function", // 显式指定为 function
            function: {
              name: tc.function.name,
              arguments: tc.function.arguments,
            },
          })),
        };
        messages.push(assistantMsg);

        for (const tc of toolCalls) {
          if (tc.type && tc.type !== 'function') continue;

          const fnName = tc.function.name;
          const argsStr = tc.function.arguments;
          if (!fnName) continue;

          let resultStr = "";
          try {
            const args = JSON.parse(argsStr || "{}");
            if (fnName === "bing_search") {
              const bing = new BingSearch();
              resultStr = await bing.search(args.query);
            } else {
              const tool = adapter.tools.find((t) => t.name === fnName);
              if (tool) {
                resultStr = await tool.call(args);
              } else {
                resultStr = JSON.stringify({ error: "Tool not found" });
              }
            }
          } catch (e: any) {
            resultStr = JSON.stringify({ error: e.message });
          }

          messages.push({
            role: "tool",
            tool_call_id: tc.id!,
            content: resultStr,
          });
        }

        // 递归流式调用
        yield* streamGenerator(client, messages, adapter);
      }
    };

    yield* streamGenerator(this.client, currentMessages, this);
  }
}